lzc-sdk-version: "0.1"
usage: "详细使用说明和 API 参考请访问：应用域名/help"

application:
  subdomain: flaresolverr
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://flaresolverr:8191/
    - location: /help
      backend: file:///lzcapp/pkg/content/

services:
  flaresolverr:
    # upstream: ghcr.io/flaresolverr/flaresolverr:v3.5.2
    image: ghcr.1ms.run/flaresolverr/flaresolverr:v3.5.2
    environment:
      - LOG_LEVEL={{.U.log_level}}
      - LOG_FILE={{.U.log_file}}
      - LOG_HTML={{.U.log_html}}
      - CAPTCHA_SOLVER={{.U.captcha_solver}}
      - TZ={{.U.tz}}
      - PROXY_USERNAME={{.U.proxy_username}}
      - PROXY_PASSWORD={{.U.proxy_password}}
      - LANG={{.U.lang}}
    binds:
      - /lzcapp/var/flaresolver:/config
    cpu_shares: 512
    mem_limit: 512M
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:8191/health || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
